// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwLH6XWAIgW27lx38RJCkswzHVeBccu9U',
    appId: '1:930267087384:web:fc550a23e511a4a7d6f96d',
    messagingSenderId: '930267087384',
    projectId: 'tts09b',
    authDomain: 'tts09b.firebaseapp.com',
    storageBucket: 'tts09b.appspot.com',
    measurementId: 'G-HXT5B3D8L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5iI3EisvHfQLUyriaIVoLOGtQu8s9zE',
    appId: '1:930267087384:android:155a47ab82d7cf48d6f96d',
    messagingSenderId: '930267087384',
    projectId: 'tts09b',
    storageBucket: 'tts09b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKa4V7Fl92gl5rFrseMg9VLxodb_KsRWs',
    appId: '1:930267087384:ios:6d76de7066d37064d6f96d',
    messagingSenderId: '930267087384',
    projectId: 'tts09b',
    storageBucket: 'tts09b.appspot.com',
    iosBundleId: 'com.example.tts09b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKa4V7Fl92gl5rFrseMg9VLxodb_KsRWs',
    appId: '1:930267087384:ios:6d76de7066d37064d6f96d',
    messagingSenderId: '930267087384',
    projectId: 'tts09b',
    storageBucket: 'tts09b.appspot.com',
    iosBundleId: 'com.example.tts09b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwLH6XWAIgW27lx38RJCkswzHVeBccu9U',
    appId: '1:930267087384:web:4f97ca46ea5ef736d6f96d',
    messagingSenderId: '930267087384',
    projectId: 'tts09b',
    authDomain: 'tts09b.firebaseapp.com',
    storageBucket: 'tts09b.appspot.com',
    measurementId: 'G-KQGRFV3CDE',
  );
}
